# Generated by Django 5.1.5 on 2025-05-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_author_delete_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Contact',
        ),
    ]
